name: Disable Checking ServerName

on:
  workflow_dispatch:
  push:
    branches:
      - main  # 监测 main 分支的推送
    paths-ignore:
      - '.github/workflows/**'  # 忽略 .github/workflows 目录下的所有文件

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: modify
        run: |
          cd tailscale
          sed -i '/hi.ServerName != m.hostname/,+2d' cmd/derper/cert.go

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN }}
          
      - name: Get latest Git tag
        id: get_tag # 为步骤添加ID，方便后续引用输出
        run: |
          cd tailscale
          git fetch --tags
          LatestTag=$(git tag --sort=-creatordate | grep -v "pre" | head -n 1)
          echo "最新版本tag: $LatestTag"
          # 将变量写入GITHUB_OUTPUT，供后续步骤使用
          echo "tag=$LatestTag" >> $GITHUB_ENV
          
      # Runs a single command using the runners shell
      - name: Build and push Docker images to docker.io and ghcr.io
        uses: docker/build-push-action@v6
        with:
          file: 'Dockerfile'
          platforms: linux/amd64,linux/arm64
          context: ./
          push: true
          tags: |
            haohaodc/ip_derper:${{ env.tag }}  # 使用env变量方式
            ghcr.io/haohaoget/ip_derper:${{ env.tag }}

