name: 'Submodules Sync'

on:
  #schedule:
  #- cron: "0 2 * * *"
  # Allows you to run this workflow manually from the Actions tab or through HTTP API
  workflow_dispatch:

jobs:
  sync:
    name: 'Submodules Sync'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.TOKEN }}
        submodules: true

    # Update references
    - name: Git Sumbodule Update
      run: |
        git pull --recurse-submodules
        #git submodule sync --recursive
        #git submodule update --remote --recursive --init --checkout $(git describe --tags --abbrev=0)
        git submodule update --remote --recursive
        git -C tailscale fetch --tags
        
        git -C tailscale checkout v1.72.0
        #获取最新版本tag
        LatestTag=$(git tag -n --sort=-taggerdate | head -n 1)
        echo -e "最新版本tag......"
        echo -e "$LatestTag"


    - name: Commit update
      run: |
        git config --global user.name 'Git bot'
        git config --global user.email 'bot@noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.TOKEN }}@github.com/${{ github.repository }}
        git commit -am "Auto updated submodule references" && git push || echo "No changes to commit"
